import javax.swing.*;
import java.util.ArrayList;

public class Tablero {
    ArrayList<Ubicacion> posicion;
    Mina mina;
    private JButton button1;
    private JPanel panel1;
    private JButton bot10;
    private JButton bot11;
    private JButton bot01;
    private JButton bot02;
    private JButton bot03;
    private JButton bot04;
    private JButton bot05;
    private JButton bot06;
    private JButton bot07;
    private JButton bot08;
    private JButton bot09;
    private JButton bot12;
    private JButton bot13;
    private JButton bot14;
    private JButton bot15;
    private JButton bot16;
    private JButton bot17;
    private JButton bot18;
    private JButton bot19;
    private JButton bot20;
    private JButton bot21;
    private JButton bot22;
    private JButton bot23;
    private JButton button24;
    private JButton button25;
    private JButton button26;
    private JButton button27;
    private JButton button28;
    private JButton button29;
    private JButton button32;
    private JButton button33;
    private JButton button34;
    private JButton button35;
    private JButton button36;
    private JButton button37;
    private JButton button38;
    private JButton button39;
    private JButton button40;
    private JButton button41;
    private JButton button42;
    private JButton button43;
    private JButton button44;
    private JButton button45;
    private JButton button46;
    private JButton button47;
    private JButton button48;
    private JButton button49;
    private JButton button50;
    private JButton button51;
    private JButton button52;
    private JButton button53;
    private JButton button54;
    private JButton button55;
    private JButton button56;
    private JButton button57;
    private JButton button58;
    private JButton button59;
    private JButton button60;
    private JButton button61;
    private JButton button62;
    private JButton button63;
    private JButton button64;
    private JButton button65;
    private JButton button66;
    private JButton button67;
    private JButton button68;
    private JButton button69;
    private JButton button70;
    private JButton button71;
    private JButton button72;
    private JButton button73;
    private JButton button74;
    private JButton button75;
    private JButton button76;
    private JButton button77;
    private JButton button78;
    private JButton button79;
    private JButton button80;
    private JButton button81;
    private JButton button82;
    private JButton button83;
    private JButton button84;
    private JButton button85;
    private JButton button86;
    private JButton button87;
    private JButton button88;
    private JButton button89;
    private JButton button90;
    private JButton bot00;
    private JButton button30;
    private JButton button31;
    private JButton bot32;
    private JButton bot33;
    private JButton bot34;
    private JButton bot35;
    private JButton bot36;
    private JButton bot37;
    private JButton bot38;
    private JButton bot39;
    private JButton bot40;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
