import javax.swing.*;
import java.util.ArrayList;

public class Tablero {
    ArrayList<Ubicacion> posicion;
    Mina mina;
    private JButton Button_reset;
    private JPanel panel1;
    private JButton bot10;
    private JButton bot11;
    private JButton bot01;
    private JButton bot02;
    private JButton bot03;
    private JButton bot04;
    private JButton bot05;
    private JButton bot06;
    private JButton bot07;
    private JButton bot08;
    private JButton bot09;
    private JButton bot12;
    private JButton bot13;
    private JButton bot14;
    private JButton bot15;
    private JButton bot16;
    private JButton bot17;
    private JButton bot18;
    private JButton bot19;
    private JButton bot20;
    private JButton bot21;
    private JButton bot22;
    private JButton bot23;
    private JButton bot24;
    private JButton bot25;
    private JButton bot26;
    private JButton bot27;
    private JButton bot28;
    private JButton bot29;
    private JButton bot41;
    private JButton bot42;
    private JButton bot43;
    private JButton bot44;
    private JButton bot45;
    private JButton bot46;
    private JButton bot47;
    private JButton bot48;
    private JButton bot49;
    private JButton bot50;
    private JButton bot51;
    private JButton bot52;
    private JButton bot53;
    private JButton bot54;
    private JButton bot55;
    private JButton bot56;
    private JButton bot57;
    private JButton bot58;
    private JButton bot59;
    private JButton bot60;
    private JButton bot61;
    private JButton bot62;
    private JButton bot63;
    private JButton bot64;
    private JButton bot65;
    private JButton bot66;
    private JButton bot67;
    private JButton bot68;
    private JButton bot69;
    private JButton bot70;
    private JButton bot80;
    private JButton bot90;
    private JButton bot71;
    private JButton bot81;
    private JButton bot91;
    private JButton bot72;
    private JButton bot82;
    private JButton bot92;
    private JButton bot73;
    private JButton bot74;
    private JButton bot75;
    private JButton bot76;
    private JButton bot77;
    private JButton bot78;
    private JButton bot79;
    private JButton bot83;
    private JButton bot84;
    private JButton bot85;
    private JButton bot86;
    private JButton bot87;
    private JButton bot88;
    private JButton bot89;
    private JButton bot93;
    private JButton bot94;
    private JButton bot95;
    private JButton bot96;
    private JButton bot97;
    private JButton bot98;
    private JButton bot99;
    private JButton bot00;
    private JButton bot30;
    private JButton bot31;
    private JButton bot32;
    private JButton bot33;
    private JButton bot34;
    private JButton bot35;
    private JButton bot36;
    private JButton bot37;
    private JButton bot38;
    private JButton bot39;
    private JButton bot40;
    private JButton Button_Salir;
    private JButton Button_inicio;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
